### ISSUE TITLE
Error running fepgen in tools/prep_mutation_fep.py for mutations involving GLY

### ISSUE THREAD

**Issue by YumizSui** [shunsakuraba/fepsuite#4]
Hi,

When attempting to prepare mutations in [PDB:7VYT](https://www.rcsb.org/structure/7VYT)(chain A, B, C) that involve mutating GLY to another residue or mutating a residue to GLY, an error occurs when running `fepgen` via the `tools/prep_mutation_fep.py` script.

For example, when trying to perform the B:S100G mutation, the following error is encountered:

```
python3 $FEPSUITE_DIR/feprest/tools/prep_mutation_fep.py --faspr $FEPSUITE_DIR/feprest/FASPR/FASPR --pdb 7vyt_colab.pdb --mutation B:S100G --ff amber14sb_OL15_fs1

Error details:
>> /path/to/fepgen -A ../wt/conf.pdb -B ../B:S100G/conf.pdb -a ../wt/topol_can.top -b ../B:S100G/topol_can.top -O fepbase.pdb -o fepbase.top --structureOA fepbase_A.pdb --structureOB fepbase_B.pdb --protein --honor-resnames --generate-restraint CA --disable-cmap-error
DEBUG: dictionary size: 30
Atoms assigned:
Assigned:
 A:SER:100:N -> A:GLY:100:N dist = 0
 A:SER:100:H -> A:GLY:100:H dist = 0
 A:SER:100:CA -> A:GLY:100:CA dist = 0
 A:SER:100:HA -> A:PHE:100:HA dist = 20.144
 A:SER:100:CB -> A:PHE:100:CB dist = 19.7428
 A:SER:100:C -> A:GLY:100:C dist = 0
 A:SER:100:O -> A:GLY:100:O dist = 0
Unssigned in A:
 A:SER:100:HB1
 A:SER:100:HB2
 A:SER:100:OG
 A:SER:100:HG
 A:PHE:100:HA
 A:PHE:100:CB
Unassigned in B:
 A:GLY:100:HA1
 A:GLY:100:HA2
*** Warning: unmatched connectivity ***
100:CA(A): N HA CB C 
100:CA(B): N C HA1 HA2 
Sanity check: 
i = 3080, Ai = 3080, Bi = 3080
BofA[Ai] = 3080, Anames[Ai] = CA
AofB[Bi] = 3080, Bnames[Bi] = CA
Raw As: 3078 3081 3082 3087
Raw Bs: 3078 3087 5036 5037
*** Warning: unmatched connectivity ***
100:HA(A): CA 
100:HA(B): CA 
Sanity check: 
i = 3081, Ai = 3081, Bi = 4851
BofA[Ai] = 4851, Anames[Ai] = HA
AofB[Bi] = 3081, Bnames[Bi] = HA
Raw As: 3080
Raw Bs: 4854
*** Warning: unmatched connectivity ***
100:CB(A): CA HB1 HB2 OG 
100:CB(B): CA HB1 HB2 CG 
Sanity check: 
i = 3082, Ai = 3082, Bi = 4852
BofA[Ai] = 4852, Anames[Ai] = CB
AofB[Bi] = 3082, Bnames[Bi] = CB
Raw As: 3080 3083 3084 3085
Raw Bs: 4854 4857 4858 4859
*** Warning: unmatched connectivity ***
100:CA(A): N HA CB C 
100:CA(B): HA CB N C 
Sanity check: 
i = 4854, Ai = 4854, Bi = 4850
BofA[Ai] = 4850, Anames[Ai] = CA
AofB[Bi] = 4854, Bnames[Bi] = CA
Raw As: 4852 4855 4856 4870
Raw Bs: 3081 3082 4852 4870
*** Warning: unmatched connectivity ***
100:HB1(A): CB 
100:HB1(B): CB 
Sanity check: 
i = 4857, Ai = 4857, Bi = 4853
BofA[Ai] = 4853, Anames[Ai] = HB1
AofB[Bi] = 4857, Bnames[Bi] = HB1
Raw As: 4856
Raw Bs: 3082
*** Warning: unmatched connectivity ***
100:HB2(A): CB 
100:HB2(B): CB 
Sanity check: 
i = 4858, Ai = 4858, Bi = 4854
BofA[Ai] = 4854, Anames[Ai] = HB2
AofB[Bi] = 4858, Bnames[Bi] = HB2
Raw As: 4856
Raw Bs: 3082
*** Warning: unmatched connectivity ***
100:CG(A): CB CD1 CD2 
100:CG(B): CB CD1 CD2 
Sanity check: 
i = 4859, Ai = 4859, Bi = 4855
BofA[Ai] = 4855, Anames[Ai] = CG
AofB[Bi] = 4859, Bnames[Bi] = CG
Raw As: 4856 4860 4868
Raw Bs: 3082 4860 4868
Number of warning exceeds max-warning
Traceback (most recent call last):
  File "/path/to/fepsuite/feprest/tools/prep_mutation_fep.py", line 447, in <module>
    dirname, refdirs = generator.generate(args.mutation, args.mutation, base_muts=args.base_mutation, base_name=args.base_mutation, base_mut_separator=args.base_mut_separator)
  File "/path/to/fepsuite/feprest/tools/prep_mutation_fep.py", line 376, in generate
    check_call_verbose([f"{self.fepsuite}/feprest/fepgen/fepgen"] + f"-A ../{fepdir[0]}/conf.pdb -B ../{fepdir[1]}/conf.pdb -a ../{fepdir[0]}/topol_can.top -b ../{fepdir[1]}/topol_can.top -O fepbase.pdb -o fepbase.top --structureOA fepbase_A.pdb --structureOB fepbase_B.pdb --protein --honor-resnames --generate-restraint CA --disable-cmap-error".split())
  File "/path/to/fepsuite/feprest/tools/prep_mutation_fep.py", line 33, in check_call_verbose
    subprocess.check_call(cmdline)
  File "/path/to/miniforge3/envs/fepsuite/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['fepsuite/feprest/fepgen/fepgen', '-A', '../wt/conf.pdb', '-B', '../B:S100G/conf.pdb', '-a', '../wt/topol_can.top', '-b', '../B:S100G/topol_can.top', '-O', 'fepbase.pdb', '-o', 'fepbase.top', '--structureOA', 'fepbase_A.pdb', '--structureOB', 'fepbase_B.pdb', '--protein', '--honor-resnames', '--generate-restraint', 'CA', '--disable-cmap-error']' returned non-zero exit status 1.
```
[7vyt_protein_ABC.pdb.txt](https://github.com/shunsakuraba/fepsuite/files/14627978/7vyt_protein_ABC.pdb.txt)

Notably, the tutorial example using 2LZM works fine for mutations involving GLY, and other mutations in 7VYT that don't involve GLY also work without issues in the preparation step.

Is this error due to an issue with the PDB structure, or could it be a bug in fepgen?

I hope this issue report is helpful in some way. Please let me know if any additional details would be useful.

My bests.

**Comment by shunsakuraba** [comment]
This is presumably because GROMACS `pdb2gmx -merge all` converts all chain IDs to chain "A". `fepgen` gets confused because all atoms with same residue numbers are mixed up (but `fepgen` also needs the target to be a single `[ moleculetype ]` entry, so `-merge all` is necessary.) A possible workaround is renumber the residue IDs using e.g. [pdb-tools](https://pypi.org/project/pdb-tools/) so that there are no overlap.

**Comment by YumizSui** [comment]
I sincerely appreciate your response and your handling of the issue.
Preparation step worked correctly.

**Comment by shunsakuraba** [comment]
I will fix this issue on upcoming release.
